18-Rails/Moma/config/routes.rb
# == Route Map
#
#      Prefix Verb   URI Pattern                 Controller#Action
#     artists GET    /artists(.:format)          artists#index
#             POST   /artists(.:format)          artists#create
#  new_artist GET    /artists/new(.:format)      artists#new
# edit_artist GET    /artists/:id/edit(.:format) artists#edit
#      artist GET    /artists/:id(.:format)      artists#show
#             PATCH  /artists/:id(.:format)      artists#update
#             PUT    /artists/:id(.:format)      artists#update
#             DELETE /artists/:id(.:format)      artists#destroy
#       works GET    /works(.:format)            works#index
#             POST   /works(.:format)            works#create
#    new_work GET    /works/new(.:format)        works#new
#   edit_work GET    /works/:id/edit(.:format)   works#edit
#        work GET    /works/:id(.:format)        works#show
#             PATCH  /works/:id(.:format)        works#update
#             PUT    /works/:id(.:format)        works#update
#             DELETE /works/:id(.:format)        works#destroy
#

Rails.application.routes.draw do
  resources :artists, :works
end

18-Rails/Moma/app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  nationality :string(255)
#  dob         :date
#  period      :string(255)
#  image       :text
#  created_at  :datetime
#  updated_at  :datetime
#

class Artist < ActiveRecord::Base
	has_many :works
end

18-Rails/Moma/app/models/work.rb
# == Schema Information
#
# Table name: works
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  year       :string(255)
#  medium     :string(255)
#  style      :string(255)
#  image      :text
#  created_at :datetime
#  updated_at :datetime
#

class Work < ActiveRecord::Base
	belongs_to :artist
end

18-Rails/Moma/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

18-Rails/Moma/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
	def index
		@artists = Artist.all 	 # Calls out all the artists into a variable to show !
	end

	def new
		@artist = Artist.new
	end

	def create
		artist = Artist.create artist_params
		redirect_to artist
	end

	def show
		@artist = Artist.find params[:id]
	end

	def edit
		@artist = Artist.find params[:id]
	end

	def update
		artist = Artist.find params[:id]
		artist.update artist_params
		redirect_to artist
	end

	def destroy
		artist = Artist.find params[:id]
		artist.destroy
		redirect_to artists_path
	end

	private 	# Strong params to protect your params
	def artist_params
		params.require(:artist).permit(:name, :nationality, :dob, :period, :image)
	end 

end

18-Rails/Moma/app/controllers/works_controller.rb
class WorksController < ApplicationController
	def index
		@works = Work.all
	end

	def new
		@work = Work.new
	end

	def create
		work = Work.create work_params
		redirect_to work
	end

	def show
		@work = Work.find params[:id]
	end

	def edit
		@work = Work.find params[:id]
	end

	def update
		work = Work.find params[:id]
		work.update work_params
		redirect_to work
	end

	def destroy
		work = Work.find params[:id]
		work.destroy
		redirect_to works_path
	end

	private
	def work_params
		params.require(:work).permit(:title, :year, :medium, :style, :image, :artist_id)
	end


end

18-Rails/Moma/app/helpers/application_helper.rb
module ApplicationHelper
end

18-Rails/Moma/app/views/artists/_form.html.erb
<%= form_for @artist do |f| %>
<p>
	<%= f.label :name  , "Name:" %>
	<%= f.text_field :name %>
</p>
<p>
	<%= f.label :nationality  , "Nationality:" %>
	<%= f.text_field :nationality %>
</p>
<p>
	<%= f.label :dob  , "DOB:" %>
	<%= f.text_field :dob %>
</p>
<p>
	<%= f.label :period  , "Period:" %>
	<%= f.text_field :period %>
</p>
<p>
	<%= f.label :image  , "Image:" %>
	<%= f.url_field :image %>
</p>
	<label></label>
	<%= f.submit %>
<% end %>

18-Rails/Moma/app/views/artists/edit.html.erb
<h1>Edit Artist</h1>
<%= render :partial => 'form' %> 	<!-- # It knows to look for _form.erb -->

18-Rails/Moma/app/views/artists/index.erb
<% @artists.each do |artist|  %>
	<ul>
		<li> <%= image_tag(artist.image, :class => 'thumbnail')  %></li>
		<li>Name: <%= link_to(artist.name, artist_path(artist)) %> </li> 
			<!-- Can also do: # link_to(artist.name, artist) -->
		<li>Nationality: <%= artist.nationality %> </li>
		<li>Period: <%= artist.period %> </li>
		<li>DOB: <%= artist.dob.strftime('%A %B %d %Y') if artist.dob %> </li>

	</ul>

<% end %>

18-Rails/Moma/app/views/artists/new.html.erb
<h1>New Artist</h1>
<%= render :partial => 'form' %> 	<!-- # It knows to look for _form.erb -->

18-Rails/Moma/app/views/artists/show.html.erb
<h1>This is the page about the <%= @artist.name.upcase  %></h1>
<%= image_tag(@artist.image, :class => 'thumbnail') %> 

<%= link_to 'Delete', @artist, :method => :delete, :data => { :confirm => "Are you sure?" } %>  <!-- artist_path(@artist.id) -->

<%= link_to 'Edit', edit_artist_path(@artist)  %>

<h3>Works</h3>
<% @artist.works.each do |work| %>
	<%= link_to work.title, work  %>
<% end %>